import pt from './pt-BR.js';

export default {
  ...pt,
  locale: 'en', languageName: 'EN', htmlLang: 'en', ogLocale: 'en_US',
  title: 'Rebeca Nonato — Software Engineer | Backend & Distributed Systems',
  description: 'Software Engineer with 10+ years building systems, focused on backend, distributed systems, event-driven architecture and reliability.',
  navLabel: 'Portfolio sections',
  nav: { about: 'About', projects: 'Projects', experience: 'Experience', skills: 'Skills', education: 'Education', contact: 'Contact', services: 'Services', arcade: 'Arcade', resources: 'Resources' },
  a11y: { ...pt.a11y, skip: 'Skip to main content', external: 'opens in a new tab', reading: 'Reading:', decrease: 'Decrease font size', increase: 'Increase font size', contrast: 'Toggle high contrast', motion: 'Reduce animation and motion', dark: 'Switch to dark theme', light: 'Switch to light theme', backTop: 'Back to top', open: 'Open navigation menu', close: 'Close navigation menu' },
  languageLabel: 'Language',
  hero: { ...pt.hero, eyebrow: 'Software Engineer · Backend & Distributed Systems', headline: 'I build backend systems', headlineAccent: 'that need to keep working.', nameRole: 'Rebeca Nonato / Software Engineer', focus: 'Backend · Distributed Systems · Event-Driven · Cloud', stack: 'Kotlin · Java · Node.js · AWS · Kafka', techLabel: 'Main technologies', projects: 'View projects', contact: 'Contact', resume: 'Resume', diagramNote: 'designed for failure, recovery and change' },
  sections: { selectedEyebrow: 'Selected Engineering Work', projectsTitle: 'Selected Projects', projectsIntro: 'Engineering decisions documented in public code — from domain to deployment.', profileEyebrow: 'Profile', aboutTitle: 'Engineering for real systems.', experienceEyebrow: 'Experience', experienceTitle: 'Professional journey', experienceIntro: '10+ years building, modernizing and operating systems.', capabilitiesEyebrow: 'Capabilities', capabilitiesTitle: 'Engineering by domain', capabilitiesIntro: 'Tools in service of architecture, reliability and evolution.', learningEyebrow: 'Learning', educationTitle: 'Education & Certifications', writingEyebrow: 'Writing', publicationsTitle: 'Publications', underEyebrow: 'Under the hood', machineTitle: 'Built for humans and machines', machineText: 'This portfolio uses semantic HTML and prerendered content so it can be read by people, search engines and agents — without compromising accessibility.', contactEyebrow: 'Start a conversation', contactTitle: 'Let’s build reliable systems.' },
  contexts: { ClinicFiapApp: 'Academic collaborative project', Food: 'Academic project', Hedge: 'Independent Software Engineering Research', Quotes: 'Personal project · MVP', TechChallenge: 'Academic project', Kube: 'Infrastructure lab', default: 'Public project' },
  projectLink: 'View repository', stackLabel: 'Technologies and patterns', flowLabel: 'Simplified flow for',
  projectDescriptions: { ClinicFiapApp: '<p>Academic collaborative distributed backend organized as services with asynchronous communication.</p><ul><li><strong>Consistency:</strong> Outbox Pattern for reliable event publishing.</li><li><strong>Reads:</strong> CQRS with an event-fed history service.</li><li><strong>Resilience:</strong> idempotent Kafka consumers and DLQ failure handling.</li></ul>', Food: '<p>Academic Java 21 and Spring Boot project following Clean Architecture.</p><ul><li><strong>Architecture:</strong> dependency rules automatically verified with ArchUnit.</li><li><strong>Quality:</strong> unit and integration tests with a JaCoCo quality gate.</li><li><strong>Infrastructure:</strong> PostgreSQL, MinIO, Docker and Docker Compose.</li></ul>', Hedge: '<p>Independent Software Engineering Research project detecting Eager Test in Java projects by selectively combining static analysis and AI.</p><ul><li><strong>Static analysis:</strong> tree-sitter extracts ASTs and test-method features.</li><li><strong>LLM gating:</strong> models are queried only for heuristic uncertainty.</li><li><strong>Ensemble:</strong> combined predictions evaluated with Precision, Recall, F1, MCC and AUC.</li></ul>', Quotes: '<p>Kotlin insurance-domain MVP focused on business-rule modeling and DDD.</p><ul><li>Quote engine with explicit approval and rejection rules.</li><li>Functional validation with Either for business errors.</li><li>Domain events and asynchronous coroutine processing.</li></ul>', TechChallenge: '<p>Academic Java 21 project using Hexagonal Architecture to isolate the domain.</p><ul><li><strong>Security:</strong> Spring Security, JWT and RBAC.</li><li><strong>Quality:</strong> SOLID, MapStruct, global exception handling and automated tests.</li></ul>', Kube: '<p>Infrastructure lab deploying a Node.js/Express API and PostgreSQL on local Kubernetes with Deployments, Services, ConfigMaps and Secrets.</p>' },
  about: ['My background combines corporate systems, application modernization, distributed backend and production operations. Today I focus on Kotlin, Java and Node.js/TypeScript, messaging, event-driven architecture and AWS environments.', 'I work with critical systems, observability, incidents, CI/CD and architectural decisions under real constraints of consistency, availability and change. In public projects, I make those decisions verifiable through tests, architectural boundaries and technical documentation.'],
  experienceIntro: { Alice: 'Backend development with Kotlin and Spring Boot, owning features end to end from modeling and technical definition through implementation, testing, deployment and production follow-up. Feature lead participation in complex work involving event-driven systems, PostgreSQL, messaging, reliability, incident investigation, mentoring and cross-team collaboration.', AccentureSpecialist: 'Promoted to Specialist in recognition of technical leadership. Technical reference in a microservices environment with more than 50 Lambdas using Node.js, Kotlin and Java/Spring Boot, including recovery of a critical Kotlin legacy system and P1/P2 incident response.', AccentureSenior: 'Worked across consulting projects with distributed and serverless backends. Node.js runtime modernization, query optimization, CloudWatch log analysis, SQS/Kafka messaging, CI/CD pipelines and Datadog observability.', Vetta: 'C#/.NET, React and Angular development focused on performance, SQL Server tuning and recovery of legacy projects through reverse engineering and refactoring.', FUNDECC: 'C#/.NET REST APIs integrating payment gateways, branch and environment deployments, and production incident resolution.', AccentureLegacy: 'Maintenance of high-availability corporate Mainframe systems with Natural/Adabas, log analysis, batch optimization and critical JCL jobs.', UFLA: 'Taught algorithms, programming languages and SQL and NoSQL databases.' },
  domains: [{ number: '01', category: 'Backend', primary: 'Kotlin · Java · Node.js', items: ['Spring Boot', 'NestJS', 'PostgreSQL'] }, { number: '02', category: 'Distributed Systems', primary: 'Kafka · SQS', items: ['Event-Driven', 'CQRS', 'Outbox', 'Idempotency'] }, { number: '03', category: 'Architecture', primary: 'DDD · Clean Architecture', items: ['Hexagonal', 'Microservices', 'Multi-Tenant'] }, { number: '04', category: 'Cloud & Reliability', primary: 'AWS · Docker · Kubernetes', items: ['Datadog', 'CloudWatch', 'CI/CD', 'DLQ'] }, { number: '05', category: 'Engineering Quality', primary: 'TDD · Automated testing', items: ['ArchUnit', 'Observability', 'Code review'] }],
  machineItems: ['Accessibility', 'Semantic HTML', 'Structured Data', 'JSON Resume', 'LLM-readable', 'Prerendered content'], contactIntro: 'Open to opportunities and conversations about backend, distributed systems, reliability and software architecture.', footer: { contact: 'Contact', explore: 'Explore', formats: 'Resume formats', note: 'Built with accessibility (WCAG) and AI-agent readability in mind.', resumeJson: 'JSON (resume.json)' },
};
