import pt from './pt-BR.js';

export default {
  ...pt,
  locale: 'zh-CN', languageName: '中文', htmlLang: 'zh-CN', ogLocale: 'zh_CN',
  title: 'Rebeca Nonato — Software Engineer | Backend & Distributed Systems',
  description: '拥有十多年系统开发经验的软件工程师，专注于 Backend、Distributed Systems、Event-Driven Architecture 与可靠性。',
  navLabel: '作品集导航',
  nav: { about: '关于我', projects: '项目', experience: '经历', skills: '技能', education: '教育', contact: '联系', services: '服务', arcade: 'Arcade', resources: '资源' },
  a11y: { ...pt.a11y, skip: '跳转到主要内容', external: '在新标签页打开', reading: '阅读：', decrease: '减小字体', increase: '增大字体', contrast: '切换高对比度', motion: '减少动画和动效', dark: '深色主题', light: '浅色主题', open: '打开导航菜单', close: '关闭导航菜单' },
  languageLabel: '语言',
  hero: { ...pt.hero, eyebrow: 'Software Engineer · Backend & Distributed Systems', headline: '构建需要持续运行的', headlineAccent: 'Backend systems。', nameRole: 'Rebeca Nonato / Software Engineer', focus: 'Backend · Distributed Systems · Event-Driven · Cloud', stack: 'Kotlin · Java · Node.js · AWS · Kafka', techLabel: '主要技术', projects: '查看项目', contact: '联系我', resume: '简历', diagramNote: '为故障、恢复与变化而设计' },
  sections: { selectedEyebrow: 'Selected Engineering Work', projectsTitle: '精选工程项目', projectsIntro: '在公开代码中记录工程决策——从领域建模到部署。', profileEyebrow: 'Profile', aboutTitle: '为真实系统而做的工程。', experienceEyebrow: 'Experience', experienceTitle: '职业经历', experienceIntro: '十多年构建、现代化和维护系统的经验。', capabilitiesEyebrow: 'Capabilities', capabilitiesTitle: '按领域组织的能力', capabilitiesIntro: '让架构、可靠性和演进服务于实际目标。', learningEyebrow: 'Learning', educationTitle: '教育与认证', writingEyebrow: 'Writing', publicationsTitle: '出版物', underEyebrow: 'Under the hood', machineTitle: 'Built for humans and machines', machineText: '本作品集使用语义化 HTML 和预渲染内容，便于人、搜索引擎和 agents 阅读，同时保持可访问性。', contactEyebrow: 'Start a conversation', contactTitle: 'Let’s build reliable systems.' },
  contexts: { ClinicFiapApp: '学术协作项目', Food: '学术项目', Hedge: 'Independent Software Engineering Research', Quotes: '个人项目 · MVP', TechChallenge: '学术项目', Kube: '基础设施实验室', default: '公开项目' },
  projectLink: '查看仓库', stackLabel: '技术与模式', flowLabel: '简化流程：',
  projectDescriptions: { ClinicFiapApp: '<p>学术协作的分布式 Backend，由多个服务组成并采用异步通信。</p><ul><li><strong>一致性：</strong>使用 Outbox Pattern 可靠发布事件。</li><li><strong>读取：</strong>使用事件驱动的 CQRS 历史服务。</li><li><strong>韧性：</strong>幂等 Kafka consumers 与 DLQ 故障处理。</li></ul>', Food: '<p>基于 Java 21 和 Spring Boot 的学术项目，遵循 Clean Architecture。</p><ul><li><strong>架构：</strong>通过 ArchUnit 自动验证依赖规则。</li><li><strong>质量：</strong>单元测试、集成测试与 JaCoCo quality gate。</li><li><strong>基础设施：</strong>PostgreSQL、MinIO、Docker 与 Docker Compose。</li></ul>', Hedge: '<p>Independent Software Engineering Research 项目，通过选择性结合 static analysis 与 AI 检测 Java 项目中的 Eager Test。</p><ul><li><strong>Static analysis：</strong>使用 tree-sitter 提取 AST 和测试方法特征。</li><li><strong>LLM gating：</strong>仅在启发式判断不确定时调用模型。</li><li><strong>Ensemble：</strong>组合预测并使用 Precision、Recall、F1、MCC 和 AUC 评估。</li></ul>', Quotes: '<p>使用 Kotlin 构建的保险领域 MVP，专注于业务规则建模与 DDD。</p><ul><li>明确的报价、批准和拒绝规则。</li><li>使用 Either 进行业务错误的函数式校验。</li><li>领域事件与 coroutine 异步处理。</li></ul>', TechChallenge: '<p>使用 Java 21 和 Hexagonal Architecture 隔离领域的学术项目。</p><ul><li><strong>安全：</strong>Spring Security、JWT 和 RBAC。</li><li><strong>质量：</strong>SOLID、MapStruct、全局异常处理与自动化测试。</li></ul>', Kube: '<p>基础设施实验室：在本地 Kubernetes 上部署 Node.js/Express API 和 PostgreSQL，使用 Deployments、Services、ConfigMaps 与 Secrets。</p>' },
  about: ['我的经历涵盖企业系统、应用现代化、分布式 Backend 以及生产运维。目前专注于 Kotlin、Java、Node.js/TypeScript、消息传递、Event-Driven Architecture 和 AWS 环境。', '我参与关键系统、可观测性、事故处理、CI/CD，并在一致性、可用性和演进等真实约束下做架构决策。在公开项目中，我通过测试、架构边界和技术文档让这些决策可验证。'],
  experienceIntro: { Alice: '使用 Kotlin 和 Spring Boot 进行 Backend 开发，负责从建模、技术定义到实现、测试、部署和生产跟进的端到端工作。参与复杂领域的 feature lead，涉及事件驱动系统、PostgreSQL、消息传递、可靠性、事故调查、指导和跨团队协作。', AccentureSpecialist: '因技术影响力晋升为 Specialist。在包含 50 多个 Lambda 的微服务环境中担任技术参考，使用 Node.js、Kotlin 和 Java/Spring Boot，并参与关键 Kotlin legacy 系统恢复及 P1/P2 事故响应。', AccentureSenior: '参与多个分布式和 serverless Backend 咨询项目，包括 Node.js runtime 现代化、查询优化、CloudWatch 日志分析、SQS/Kafka 消息传递、CI/CD 和 Datadog 可观测性。', Vetta: '使用 C#/.NET、React 和 Angular 开发，关注性能、SQL Server 调优，并通过逆向工程和重构恢复 legacy 项目。', FUNDECC: '使用 C#/.NET 构建 REST API，集成支付网关，管理分支和环境部署，并处理生产事故。', AccentureLegacy: '维护高可用企业 Mainframe 系统，使用 Natural/Adabas，进行日志分析、批处理优化并创建关键 JCL 作业。', UFLA: '教授算法、编程语言以及 SQL 和 NoSQL 数据库。' },
  domains: [{ number: '01', category: 'Backend', primary: 'Kotlin · Java · Node.js', items: ['Spring Boot', 'NestJS', 'PostgreSQL'] }, { number: '02', category: 'Distributed Systems', primary: 'Kafka · SQS', items: ['Event-Driven', 'CQRS', 'Outbox', 'Idempotency'] }, { number: '03', category: 'Architecture', primary: 'DDD · Clean Architecture', items: ['Hexagonal', 'Microservices', 'Multi-Tenant'] }, { number: '04', category: 'Cloud & Reliability', primary: 'AWS · Docker · Kubernetes', items: ['Datadog', 'CloudWatch', 'CI/CD', 'DLQ'] }, { number: '05', category: 'Engineering Quality', primary: 'TDD · Automated testing', items: ['ArchUnit', 'Observability', 'Code review'] }],
  machineItems: ['Accessibility', 'Semantic HTML', 'Structured Data', 'JSON Resume', 'LLM-readable', 'Prerendered content'], contactIntro: '欢迎交流 Backend、分布式系统、可靠性和软件架构相关机会。', footer: { contact: '联系', explore: '探索', formats: '简历格式', note: '以 WCAG 可访问性和 AI agents 易读性为目标构建。', resumeJson: 'JSON (resume.json)' },
};
